/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

/**
 *
 * @author Karlenypc
 */
public class MainWindow extends javax.swing.JFrame {

    /**
     * Creates new form MainWindow
     */
    public MainWindow() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1_Base = new javax.swing.JPanel();
        jPanel2_Menu = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btnPaciente = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        btnMedico = new javax.swing.JButton();
        btnRegistro = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        btnCita = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        btnProcedimiento = new javax.swing.JButton();
        btnClinica = new javax.swing.JButton();
        jPanel3_Superior = new javax.swing.JPanel();
        jLabel_Menu = new javax.swing.JLabel();
        jPanel_Central = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();
        jLabel13 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel14 = new javax.swing.JLabel();
        jComboBox3 = new javax.swing.JComboBox<>();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1_Base.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1_Base.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2_Menu.setBackground(new java.awt.Color(231, 229, 218));
        jPanel2_Menu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagesIcons/icons8_google_forms_33px.png"))); // NOI18N
        jPanel2_Menu.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, 40, 40));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagesIcons/icons8_medical_doctor_33px.png"))); // NOI18N
        jPanel2_Menu.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, 40, 40));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagesIcons/icons8_search_property_33px.png"))); // NOI18N
        jPanel2_Menu.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 380, 40, 40));

        btnPaciente.setBackground(new java.awt.Color(106, 100, 90));
        btnPaciente.setFont(new java.awt.Font("Microsoft YaHei", 1, 15)); // NOI18N
        btnPaciente.setForeground(new java.awt.Color(30, 29, 26));
        btnPaciente.setText("Pacientes");
        btnPaciente.setBorder(null);
        btnPaciente.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnPaciente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mouseclicked(evt);
            }
        });
        btnPaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPacienteActionPerformed(evt);
            }
        });
        jPanel2_Menu.add(btnPaciente, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 380, 210, 41));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagesIcons/icons8_hospital_3_33px.png"))); // NOI18N
        jPanel2_Menu.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 280, 40, 40));

        btnMedico.setBackground(new java.awt.Color(106, 100, 90));
        btnMedico.setFont(new java.awt.Font("Microsoft YaHei", 1, 15)); // NOI18N
        btnMedico.setForeground(new java.awt.Color(30, 29, 26));
        btnMedico.setText("Médico");
        btnMedico.setBorder(null);
        btnMedico.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnMedico.setRolloverEnabled(true);
        btnMedico.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mouseclicked(evt);
            }
        });
        btnMedico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMedicoActionPerformed(evt);
            }
        });
        jPanel2_Menu.add(btnMedico, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 230, 210, 41));

        btnRegistro.setBackground(new java.awt.Color(106, 100, 90));
        btnRegistro.setFont(new java.awt.Font("Microsoft YaHei", 1, 15)); // NOI18N
        btnRegistro.setForeground(new java.awt.Color(30, 29, 26));
        btnRegistro.setText("Registrarse");
        btnRegistro.setBorder(null);
        btnRegistro.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnRegistro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mouseclicked(evt);
            }
        });
        btnRegistro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistroActionPerformed(evt);
            }
        });
        jPanel2_Menu.add(btnRegistro, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 180, 210, 41));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagesIcons/icons8_health_book_33px.png"))); // NOI18N
        jPanel2_Menu.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 430, 40, 40));

        btnCita.setBackground(new java.awt.Color(106, 100, 90));
        btnCita.setFont(new java.awt.Font("Microsoft YaHei", 1, 15)); // NOI18N
        btnCita.setForeground(new java.awt.Color(30, 29, 26));
        btnCita.setText("Citas");
        btnCita.setBorder(null);
        btnCita.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnCita.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mouseclicked(evt);
            }
        });
        btnCita.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCitaActionPerformed(evt);
            }
        });
        jPanel2_Menu.add(btnCita, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 430, 210, 41));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagesIcons/icons8_health_checkup_33px_1.png"))); // NOI18N
        jPanel2_Menu.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 330, 40, 40));

        btnProcedimiento.setBackground(new java.awt.Color(106, 100, 90));
        btnProcedimiento.setFont(new java.awt.Font("Microsoft YaHei", 1, 15)); // NOI18N
        btnProcedimiento.setForeground(new java.awt.Color(30, 29, 26));
        btnProcedimiento.setText("        Procedimientos");
        btnProcedimiento.setBorder(null);
        btnProcedimiento.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnProcedimiento.setRolloverEnabled(true);
        btnProcedimiento.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mouseclicked(evt);
            }
        });
        btnProcedimiento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProcedimientoActionPerformed(evt);
            }
        });
        jPanel2_Menu.add(btnProcedimiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 330, 210, 41));

        btnClinica.setBackground(new java.awt.Color(106, 100, 90));
        btnClinica.setFont(new java.awt.Font("Microsoft YaHei", 1, 15)); // NOI18N
        btnClinica.setForeground(new java.awt.Color(30, 29, 26));
        btnClinica.setText("Clínicas");
        btnClinica.setBorder(null);
        btnClinica.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnClinica.setRolloverEnabled(true);
        btnClinica.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mouseclicked(evt);
            }
        });
        btnClinica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClinicaActionPerformed(evt);
            }
        });
        jPanel2_Menu.add(btnClinica, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 280, 210, 41));

        jPanel1_Base.add(jPanel2_Menu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 210, 480));

        jPanel3_Superior.setBackground(new java.awt.Color(0, 10, 26));

        jLabel_Menu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagesIcons/icons8_menu_48px.png"))); // NOI18N
        jLabel_Menu.setPreferredSize(new java.awt.Dimension(40, 40));

        javax.swing.GroupLayout jPanel3_SuperiorLayout = new javax.swing.GroupLayout(jPanel3_Superior);
        jPanel3_Superior.setLayout(jPanel3_SuperiorLayout);
        jPanel3_SuperiorLayout.setHorizontalGroup(
            jPanel3_SuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3_SuperiorLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel_Menu, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(783, Short.MAX_VALUE))
        );
        jPanel3_SuperiorLayout.setVerticalGroup(
            jPanel3_SuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3_SuperiorLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel_Menu, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(10, Short.MAX_VALUE))
        );

        jPanel1_Base.add(jPanel3_Superior, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 820, 40));

        jPanel_Central.setLayout(new java.awt.CardLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setFont(new java.awt.Font("Segoe UI Black", 0, 16)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 10, 26));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("INFORMACION PERSONAL");
        jLabel7.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabel7.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 17, 230, 28));

        jLabel8.setBackground(new java.awt.Color(169, 164, 160));
        jLabel8.setFont(new java.awt.Font("Microsoft YaHei", 1, 13)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(30, 29, 26));
        jLabel8.setText("Nombre Padecimiento:");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 390, 160, 30));

        jTextField1.setBackground(new java.awt.Color(231, 229, 218));
        jTextField1.setFont(new java.awt.Font("Microsoft YaHei", 0, 12)); // NOI18N
        jTextField1.setForeground(new java.awt.Color(30, 29, 26));
        jTextField1.setText("jTextField1");
        jTextField1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, 230, 30));

        jLabel9.setBackground(new java.awt.Color(169, 164, 160));
        jLabel9.setFont(new java.awt.Font("Microsoft YaHei", 1, 13)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(30, 29, 26));
        jLabel9.setText("Descripción Padecimiento:");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 290, 190, 30));

        jTextField2.setBackground(new java.awt.Color(231, 229, 218));
        jTextField2.setFont(new java.awt.Font("Microsoft YaHei", 0, 12)); // NOI18N
        jTextField2.setForeground(new java.awt.Color(30, 29, 26));
        jTextField2.setText("jTextField1");
        jTextField2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 230, 30));

        jLabel10.setBackground(new java.awt.Color(169, 164, 160));
        jLabel10.setFont(new java.awt.Font("Microsoft YaHei", 1, 13)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(30, 29, 26));
        jLabel10.setText("Cédula:");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 140, 30));

        jTextField3.setBackground(new java.awt.Color(231, 229, 218));
        jTextField3.setFont(new java.awt.Font("Microsoft YaHei", 0, 12)); // NOI18N
        jTextField3.setForeground(new java.awt.Color(30, 29, 26));
        jTextField3.setText("jTextField1");
        jTextField3.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 230, 30));

        jLabel11.setBackground(new java.awt.Color(169, 164, 160));
        jLabel11.setFont(new java.awt.Font("Microsoft YaHei", 1, 13)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(30, 29, 26));
        jLabel11.setText("Correo Electrónico:");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, 140, 30));

        jLabel12.setBackground(new java.awt.Color(169, 164, 160));
        jLabel12.setFont(new java.awt.Font("Microsoft YaHei", 1, 13)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(30, 29, 26));
        jLabel12.setText("Tipo Padecimiento:");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 310, 140, 30));

        jComboBox2.setBackground(new java.awt.Color(231, 229, 218));
        jComboBox2.setFont(new java.awt.Font("Microsoft YaHei", 0, 13)); // NOI18N
        jComboBox2.setForeground(new java.awt.Color(30, 29, 26));
        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" }));
        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });
        jPanel1.add(jComboBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 420, 230, 30));

        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("FOTO???!");
        jLabel13.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 50, 170, 180));

        jTextArea1.setBackground(new java.awt.Color(231, 229, 218));
        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Microsoft JhengHei", 0, 12)); // NOI18N
        jTextArea1.setForeground(new java.awt.Color(30, 29, 26));
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 330, 280, 120));

        jLabel14.setBackground(new java.awt.Color(169, 164, 160));
        jLabel14.setFont(new java.awt.Font("Microsoft YaHei", 1, 13)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(30, 29, 26));
        jLabel14.setText("Nombre Completo:");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 140, 30));

        jComboBox3.setBackground(new java.awt.Color(231, 229, 218));
        jComboBox3.setFont(new java.awt.Font("Microsoft YaHei", 0, 13)); // NOI18N
        jComboBox3.setForeground(new java.awt.Color(30, 29, 26));
        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" }));
        jComboBox3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox3ActionPerformed(evt);
            }
        });
        jPanel1.add(jComboBox3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 340, 230, 30));

        jPanel_Central.add(jPanel1, "card2");

        jPanel2.setBackground(new java.awt.Color(255, 153, 255));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 610, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 480, Short.MAX_VALUE)
        );

        jPanel_Central.add(jPanel2, "card3");

        jPanel3.setBackground(new java.awt.Color(255, 255, 204));
        jPanel3.setForeground(new java.awt.Color(255, 255, 204));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 610, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 480, Short.MAX_VALUE)
        );

        jPanel_Central.add(jPanel3, "card4");

        jPanel4.setBackground(new java.awt.Color(51, 51, 0));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 610, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 480, Short.MAX_VALUE)
        );

        jPanel_Central.add(jPanel4, "card5");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 610, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 480, Short.MAX_VALUE)
        );

        jPanel_Central.add(jPanel5, "card6");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 610, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 480, Short.MAX_VALUE)
        );

        jPanel_Central.add(jPanel6, "card7");

        jPanel1_Base.add(jPanel_Central, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 40, 610, 480));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1_Base, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1_Base, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnProcedimientoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProcedimientoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnProcedimientoActionPerformed

    private void btnPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPacienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnPacienteActionPerformed

    private void btnMedicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMedicoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnMedicoActionPerformed

    private void btnClinicaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClinicaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnClinicaActionPerformed

    private void btnCitaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCitaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCitaActionPerformed

    private void btnRegistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRegistroActionPerformed

    private void mouseclicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mouseclicked
        
        //Panel Slider 
        if(evt.getSource() == btnRegistro) {
            jPanel1.setVisible(true);
            jPanel2.setVisible(false);
            jPanel3.setVisible(false);
            jPanel4.setVisible(false);
            jPanel5.setVisible(false);
            jPanel6.setVisible(false);
        }
        
        if(evt.getSource() == btnMedico) {
            jPanel1.setVisible(false);
            jPanel2.setVisible(true);
            jPanel3.setVisible(false);
            jPanel4.setVisible(false);
            jPanel5.setVisible(false);
            jPanel6.setVisible(false);
        }
        
        if(evt.getSource() == btnClinica) {
            jPanel1.setVisible(false);
            jPanel2.setVisible(false);
            jPanel3.setVisible(true);
            jPanel4.setVisible(false);
            jPanel5.setVisible(false);
            jPanel6.setVisible(false);
        }
        
        if(evt.getSource() == btnProcedimiento) {
            jPanel1.setVisible(false);
            jPanel2.setVisible(false);
            jPanel3.setVisible(false);
            jPanel4.setVisible(true);
            jPanel5.setVisible(false);
            jPanel6.setVisible(false);
        }
        
        if(evt.getSource() == btnPaciente) {
            jPanel1.setVisible(false);
            jPanel2.setVisible(false);
            jPanel3.setVisible(false);
            jPanel4.setVisible(false);
            jPanel5.setVisible(true);
            jPanel6.setVisible(false);
        }
        
        if(evt.getSource() == btnCita) {
            jPanel1.setVisible(false);
            jPanel2.setVisible(false);
            jPanel3.setVisible(false);
            jPanel4.setVisible(false);
            jPanel5.setVisible(false);
            jPanel6.setVisible(true);
        }
    }//GEN-LAST:event_mouseclicked

    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox2ActionPerformed

    private void jComboBox3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainWindow().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCita;
    private javax.swing.JButton btnClinica;
    private javax.swing.JButton btnMedico;
    private javax.swing.JButton btnPaciente;
    private javax.swing.JButton btnProcedimiento;
    private javax.swing.JButton btnRegistro;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabel_Menu;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel1_Base;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel2_Menu;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel3_Superior;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel_Central;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    // End of variables declaration//GEN-END:variables
}
